Initial setup for AWS SDK
RedHatCRE/syncron pull request #15
Opened 2022-10-07 09:23 UTC by IgnacioPro

This PR introduces the AWS SDK and reads from the bucket listed under the configuration file for syncron, 
which now will be under config folder at the root of repository.
It's only the initial setup, checking if all parameters are correct for accessing the provided bucket.

2022-10-10 08:42 UTC, jsanemet requested changes
Looks good for the most part. Once you start doing more with S3, you will mostly want to move this code to a module under 'pkg'.

2022-10-10 08:42 UTC, jsanemet commented on go.mod
>  	github.com/spf13/viper v1.13.0
Run 'go mod tidy' to move 'viper' to the direct dependencies section.

2022-10-10 08:42 UTC, jsanemet commented on cmd/adhoc/cmd/root.go
> +			viper.SetConfigFile("config/syncron.yaml")
You will probably want to update '.gitignore' too.

2022-10-10 08:42 UTC, jsanemet commented on cmd/adhoc/cmd/root.go
> +				fmt.Println("Error setting up AWS...", "Check config params", err)
If the session has failed to be established, you will not want to continue with the setup. Return the error to stop flow here.

2022-10-10 08:42 UTC, jsanemet commented on cmd/adhoc/cmd/root.go
> +				fmt.Println("Unable to list items in bucket", err, resp)
Same as above.

2022-10-13 08:34 UTC, IgnacioPro commented on cmd/adhoc/cmd/root.go
> +			viper.SetConfigFile("config/syncron.yaml")
No need since .gitignore will ignore the file regardless of path.

2022-10-13 09:08 UTC, adrianfusco approved these changes
+1

2022-10-13 09:34 UTC, jsanemet approved these changes
+1

2022-10-13 09:41 UTC, merged